### ISSUE TITLE
ServiceLoader discoverability

### ISSUE THREAD

**Issue by tombentley** [strimzi/kafka-env-var-config-provider#3]
Per discussion in https://github.com/confluentinc/kafka-images/issues/102, we need to ensure the config provider is discoverable using ServiceLoader

**Comment by tombentley** [comment]
I was coming at this from the Kafka side. I see there's always #2 to resolve this.

**Comment by vutkin** [comment]
Workaround: https://github.com/confluentinc/cp-docker-images/issues/828#issuecomment-720533576

**Comment by scholzj** [comment]
@vutkin Version 0.1.0 added the Service Loader configuration. So it should be solved now.

**Comment by vutkin** [comment]
Unfortunately no, it fails with same error. Workaround helps
By the way in version 0.1.1 added the Service Loader configuration;)

**Comment by scholzj** [comment]
Yeah, sorry, I overlooked ... 0.1.1 added the ServiceLoader.
